android/plaid

- app/src/main/AndroidManifest.xml
When someone leaved the app using the back button and then tries to open the app from recents, Android shows a Toast saying "Could not start the Plaid". This is caused by the acitivity-alias and fixed by exporting the targetActivity.
https://code.google.com/p/android/issues/detail?id=82185
closes #12
> fix opening app the from recents

- app/src/main/res/values/styles.xml
Changed style values in order to avoid NPE in API21
fixes #6
Well, I haven't seen any difference if I've commented them out, but there was surely a point to setting them to @null. Turning them now to transparent should give the same effect and causes no crashes.
> Fixed NPE on pressing search for Android 5.0.1

- build.gradle
Update build tools to latest version (2.0.0-beta4) with some performance improvements especially related to the Instant Run feature. (http://tools.android.com/tech-docs/new-build-system)
> Update gradle build tools to 2.0.0-beta4

- app/src/main/java/io/plaidapp/ui/widget/BottomSheet.java
If you drag the bottom sheet all the way to the dismiss offset, the
callback was not being notified.
This can be reproduced on master fairly reliably by keeping your finger down and dragging through the nav bar and onto the bezel.
> Fix edge case for bottom sheet not being dismissed

- app/src/main/java/io/plaidapp/ui/widget/BottomSheet.java
This avoids concurrent modification exceptions if (un)registerCallback
is called while dispatching an event.
> Switch bottom sheet callbacks to CopyOnWriteArrayList

- app/src/main/java/io/plaidapp/ui/transitions/FabTransform.java
This isn't really noticable at high transition speed, but slowed down you see that the transition from the fab to an activity cuts off after approx. 75% of the animation and just jumps to the non-clipped activity. With this fix the end radius gets calculated correctly. Same for the reversed transition.
> Fix FabTransform circular reveal calculation

- app/src/main/java/io/plaidapp/ui/DesignerNewsLogin.java
emove onTransitionEnd listener after it is called to avoid username.showDropDown() be called on end transition by backpressed
> Fix of show accounts dropdown when transition is ended by backpressed issue #117

- app/src/main/java/io/plaidapp/ui/AboutActivity.java
@nickbutcher please review. I watched the presentation,  enabled the InteliJ option and fixed the AboutActivity because I previously introduced `Activity host`
> Removed synthetic accessors from AboutActivity

- app/src/main/java/io/plaidapp/ui/DribbbleShot.java
When you'd open a Dribbble post where the height was smaller than ( screenHeight - minOffset ), the dribbble_shot_description would hover the image, and improperly place the FAB where you can't post your comment.
https://goo.gl/photos/GqevB37SrKm9ogzD6
These changes fix that:
https://goo.gl/photos/R9UeT8LkP3USN2eS7
> Fix content hover issue in Dribbble post.

- app/build.gradle
- app/src/main/java/io/plaidapp/data/api/dribbble/FollowersDataManager.java
- app/src/main/java/io/plaidapp/data/api/dribbble/PlayerShotsDataManager.java
- app/src/main/java/io/plaidapp/data/api/dribbble/ShotLikesDataManager.java
- app/src/main/java/io/plaidapp/data/api/dribbble/TeamMembersDataManager.java
Upgrade to [Retrofit 2.2](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-220-2017-02-21) to pick up bug fixes etc.
Fix some warnings resulting from use of raw `Call` type.
> Upgrade to Retrofit 2.2, fix unchecked call warnings

- app/src/main/java/io/plaidapp/ui/DesignerNewsLogin.java
Check if getAuthedUser call is successful before getting the body
of the response in order to avoid a NPE.
Also, removes synthetic accessors from DesignerNewsLogin and re-
arranges methods by access modifiers
> Fixes DesignerNewsLogin NPE

- app/src/main/java/io/plaidapp/ui/HomeActivity.java
- app/src/main/java/io/plaidapp/ui/recyclerview/InfiniteScrollListener.java
It's a fix for issue #224 as proposed [here](https://guides.codepath.com/android/Endless-Scrolling-with-AdapterViews-and-RecyclerView#troubleshooting).
> Fixed warning in RecyclerView during infinite scrolling

- app/src/main/java/io/plaidapp/ui/DribbbleLogin.java
> Fix DribbbleLogin ProgressBar loading forever on Login cancel

- app/build.gradle
- build.gradle
- core/build.gradle
- designernews/build.gradle
- dribbble/build.gradle
- third_party/bypass/build.gradle
This is a step toward enabling releasing from CI. Version code still
derived from git commit count.
> Set app version name in build script instead of git tag.

- about/src/main/java/io/plaidapp/ui/about/widget/CutoutTextView.java
We're using the sync method of loading the font, which apparently
fails if the font is not available (non-GMS device?). We could
try loading it async but Roboto Mono is used extensively elsewhere
via downloadable fonts, so if it's not available here, then it's
unlikely to ever be. Instead just ignore the error.
Fixes #390
> Ignore errors loading font in CutoutTextView.

- app/build.gradle
- core/build.gradle
- core/src/main/java/io/plaidapp/core/util/ActivityHelper.kt
The current setup caused too much overhead for having two versions of the app installed at the same time. This PR removes the `.debug` package suffix and BuildConfig field for package.
> Remove build config suffixing for now

- core/src/main/java/io/plaidapp/core/designernews/domain/model/CommentWithReplies.kt
- designernews/src/main/java/io/plaidapp/designernews/domain/CommentsWithRepliesAndUsersUseCase.kt
This tweaks flattening `CommentWithReplies` with a more optimized version via recursive sequence-generating `flattenWithReplies` property. This makes the entire flattening process a single iteration with no mutable intermediate state. 
Also opportunistically changed
```kotlin
val userMapping = users.map { it.id to it }.toMap()
```
to the more idiomatic (but functionally the same sans one iteration)
```kotlin
val userMapping = users.associateBy(User::id)
```
> Optimize flattening CommentWithReplies

- designernews/src/main/java/io/plaidapp/designernews/ui/login/LoginViewModel.kt
I'm not sure whether the high probability of test fails #493  is result from this dup call, however, it is real confuse to have nested using of `launch{}` there. The `emitUiState()` has a `launch{}` already internal.
> Remove duplicate/nested launch{} call enableLogin()

- app/src/main/java/io/plaidapp/ui/recyclerview/FilterTouchHelperCallback.kt
Kotlin now sends let{} warning when it will be used directly.
> Fix warnings in FilterTouchHelperCallback

- core/src/main/java/io/plaidapp/core/producthunt/ui/ProductHuntPostHolder.kt
Kotlin now sends let{} warning when it will be used directly. Nested-call on `let{}` can bring confused local `it`.
> Fix warnings in ProductHuntPostHolder

- core/src/main/java/io/plaidapp/core/designernews/ui/stories/StoryViewHolder.kt
Kotlin now sends `let{}` warning when it will be used directly.
> Fix warnings in StoryViewHolder.kt

- app/src/androidTest/java/io/plaidapp/ui/HomeActivityTest.kt
- core/build.gradle
- core/src/androidTest/java/io/plaidapp/core/designernews/data/database/LoggedInUserDaoTest.kt
- core/src/androidTest/java/io/plaidapp/core/designernews/data/login/AuthTokenLocalDataSourceTest.kt
- core/src/androidTest/java/io/plaidapp/core/designernews/data/login/LoginLocalDataSourceTest.kt
- core/src/androidTest/java/io/plaidapp/core/dribbble/data/prefs/DribbbleV1SourceRemoverTest.kt
- core/src/androidTest/java/io/plaidapp/core/util/TextViewExtensionTest.kt
- designernews/build.gradle
- dribbble/build.gradle
- test_shared/src/main/java/io/plaidapp/test/shared/FakeAppInjection.kt
- Replace deprecated [`androidx.test.InstrumentationRegistry`](https://developer.android.com/reference/androidx/test/InstrumentationRegistry) with suggested replacement `test.platform.app.InstrumentationRegistry`
- Update deprecated import `Unconfined` to `Dispatchers.Unconfined`
- Also remove explicit declaration for coroutines as it's already included in Kotlin 1.3
> Update imports for Testing

- build.gradle
- core/src/main/java/io/plaidapp/core/AppInjection.kt
- core/src/main/java/io/plaidapp/core/dagger/CoroutinesDispatcherProviderModule.kt
- core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
- core/src/main/java/io/plaidapp/core/data/CoroutinesDispatcherProvider.kt
- core/src/main/java/io/plaidapp/core/designernews/domain/LoadStoriesUseCase.kt
- core/src/main/java/io/plaidapp/core/designernews/domain/SearchStoriesUseCase.kt
- core/src/main/java/io/plaidapp/core/dribbble/data/ShotsRepository.kt
- core/src/test/java/io/plaidapp/core/designernews/domain/LoadStoriesUseCaseTest.kt
- core/src/test/java/io/plaidapp/core/designernews/domain/SearchStoriesUseCaseTest.kt
- core/src/test/java/io/plaidapp/core/dribbble/data/ShotsRepositoryTest.kt
- designernews/build.gradle
- designernews/src/main/java/io/plaidapp/designernews/ui/DesignerNewsViewModelFactory.kt
- designernews/src/main/java/io/plaidapp/designernews/ui/login/LoginViewModel.kt
- designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryViewModel.kt
- designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryViewModelFactory.kt
- designernews/src/test/java/io/plaidapp/designernews/ui/login/LoginViewModelTest.kt
- designernews/src/test/java/io/plaidapp/designernews/ui/story/StoryViewModelTest.kt
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleModule.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotViewModel.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotViewModelFactory.kt
- dribbble/src/test/java/io/plaidapp/dribbble/ui/shot/ShotViewModelTest.kt
- test_shared/src/main/java/io/plaidapp/test/shared/FakeAppInjection.kt
ViewModels have a scope and the parent job gets cancelled in `onCleared`
Repositories and UseCases, that are still called from Java and use the mix of coroutines and callbacks, since they also offer a way of cancelling the tasks, are using the `GlobalScope` to launch coroutines.
> Using Kotlin's structured concurrency model

- designernews/build.gradle
- dribbble/build.gradle
https://github.com/nickbutcher/plaid/commit/358e6ba560b974f4afddae36070f3a99cc5f9228 and https://github.com/nickbutcher/plaid/commit/b8f243c4f32e3380aca003742802fa53abcd4356 resulted in a duplicate reference to the `lifecycle-runtime` dependency.
> Group and dedupe dependencies related to runtime classpath workaround

- core/src/main/java/io/plaidapp/core/dribbble/data/ShotsRepository.kt
ShotsRepository is a singleton that lives in the scope of the app. Once cancelAllSearches was called, no other calls could have been triggered, because the parent job was canceled (once a job was cancelled it cannot be active again. See https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/index.html ).
So for now, we're just cancelling the children.
Future, ideal fix - remove the job launching from the Repository
> Only cancel the children of the ShotsRepository.

- about/build.gradle
- app/build.gradle
- core/build.gradle
- core_dependencies.gradle
- designernews/build.gradle
- dribbble/build.gradle
- search/build.gradle
- test_dependencies.gradle
- test_shared/build.gradle
Gradle figures out where stuff is needed and where to place code in the app bundle.
This also can make incremental builds faster.
> Use implementation instead of api

- core/src/main/java/io/plaidapp/core/designernews/data/votes/UpvoteStoryService.java
The injection uses the service as a context, but the context only exists after onStart is called. So moving the injection away from the constructor and in onStart. Fixes #559
P.S. Upvoting doesn't update the UI, but it does trigger the request to the DN API, so don't worry if you don't see anything happening on the screen.
> Moves the injection to the point where the service is started.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This reflects the release of Android Studio 3.4 Canary 8.
This also requires updating Gradle to 5.1 milestone 1
> Update AGP to 3.4.0-alpha08

- core/src/main/java/io/plaidapp/core/dagger/FilterAdapterModule.kt
- core/src/main/java/io/plaidapp/core/ui/FilterAdapter.kt
The proper fix for this would use `@Singleton` from dagger, but since we're only adding scopes later (see #573 ) I'm keeping this PR small, just to fix the bug.
> [Bug fix] Feed is not updated when changing filters

- search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
Root cause: we were passing a CharSequence in the Intent extra and trying to read it as a String. This lead to getting null.
> [Bug fix] Save filter doesn't work.

- core/src/main/java/io/plaidapp/core/dagger/CoreDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/ProductHuntModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/DesignerNewsDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
This uses a pattern of deferred initialization via Retrofit's `Call.Factory` support to allow OkHttpClient (and its initialization) to be deferred until the first network request, and subsequently also move it entirely to a background thread.
I opportunistically cleaned up a couple things here too to either make it more idiomatic DI (intermediate dependencies), and also leverage use of private qualifiers to newBuilder an upstream OkHttpClient as needed rather than keep adding to a builder (which would have added those interceptors to other modules too since the builder's mutable!). This also shared the OkHttpClient instance with the dribbble module, which was otherwise just creating its own instance and doubling the connection pools.
> Defer initialization of OkHttpClient until first request

- repositories.gradle
Resolves a security vulnerability where artifacts would be resolved over HTTP instead of HTTPS.
[CWE-829: Inclusion of Functionality from Untrusted Control Sphere](https://cwe.mitre.org/data/definitions/829.html)
[CWE-494: Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)
The build files indicate that this project is resolving dependencies over HTTP instead of HTTPS. Any of these artifacts could have been MITM to maliciously compromise them and infect the build artifacts that were produced. Additionally, if any of these JARs or other dependencies were compromised, any developers using these could continue to be infected past updating to fix this.
This vulnerability has a CVSS v3.0 Base Score of 8.1/10 …
> [SECURITY] Resolve Dependencies over HTTPS

- app/src/main/java/io/plaidapp/dagger/HomeModule.kt
- app/src/main/java/io/plaidapp/ui/HomeActivity.java
- core/src/main/java/io/plaidapp/core/ui/FeedAdapter.java
- search/src/main/java/io/plaidapp/search/dagger/SearchModule.kt
- search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
* The Adapter doesn't need to be injected in the activities, the activity can just create it every time
* The `ViewPreloadSizeProvider` is specific to the Adapter so it doesn't need to be given as a constructor param.
> Cleaning FeedAdapter - step 1

- app/src/main/java/io/plaidapp/ui/HomeActivity.java
- app/src/main/java/io/plaidapp/ui/HomeViewModel.kt
- app/src/test/java/io/plaidapp/ui/HomeViewModelTest.kt
- core/src/main/java/io/plaidapp/core/feed/FeedAdapter.java
- core/src/main/java/io/plaidapp/core/feed/FeedUiModel.kt
- search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
- search/src/main/java/io/plaidapp/search/ui/SearchViewModel.kt
- search/src/test/java/io/plaidapp/search/ui/SearchViewModelTest.kt
Removing DataLoadingSubject from FeedAdapter and moving the logic to the Home and Search ViewModels
> Cleaning FeedAdapter - step 2

- core/src/main/java/io/plaidapp/core/dribbble/data/api/model/Images.kt
- core/src/main/java/io/plaidapp/core/util/BindingAdapters.kt
- designernews/src/main/res/layout/toast_logged_in_confirmation.xml
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleModule.kt
- dribbble/src/main/java/io/plaidapp/dribbble/domain/CreateShotUiModelUseCase.kt
- dribbble/src/main/java/io/plaidapp/dribbble/domain/GetShareShotInfoUseCase.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotActivity.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotBindingAdapters.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotStyler.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotUiModel.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotViewModel.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotViewModelFactory.kt
- dribbble/src/main/res/layout/activity_dribbble_shot.xml
- dribbble/src/test/java/io/plaidapp/dribbble/TestData.kt
- dribbble/src/test/java/io/plaidapp/dribbble/domain/CreateShotUiModelUseCaseTest.kt
- dribbble/src/test/java/io/plaidapp/dribbble/domain/GetShareShotInfoUseCaseTest.kt
- dribbble/src/test/java/io/plaidapp/dribbble/ui/shot/ShotViewModelTest.kt
- gradle/wrapper/gradle-wrapper.properties
Refactor Dribble Shot feature to use UiModel
Changes:
- The activity gets massively simplified with no need to bind the shot.
- BindingAdapters taken from [Nick's commit](https://github.com/nickbutcher/plaid/commit/1bbd58c6fd5dc45fef961a1f01415e24de693142). Kudos to him!
- ViewModel exposes the shotUiModel via LiveData which is consumed by the view/xml with DataBinding.
Testing:
- The app works as before.
- Tested in an emulator.
- Added more unit tests and all of them pass
> Refactor Dribbble Shot feature to use UiModel

- app/src/main/java/io/plaidapp/dagger/HomeComponent.kt
- app/src/main/java/io/plaidapp/ui/PlaidApplication.kt
- core/src/main/java/io/plaidapp/core/dagger/CoreComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/CoreDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/LocalApis.kt
- core/src/main/java/io/plaidapp/core/dagger/ProductHuntModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/DesignerNewsDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/Injector.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/UpvoteStoryServiceComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/DataModule.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/Injector.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/LoginComponent.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/StoryComponent.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/StoryModule.kt
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleComponent.kt
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleModule.kt
Tested in an emulator. Would be nice to test in a real device and try some features like login.
A Component can be useful for:
- Be injected to an app component.
- Inject modules so that other components that are Subcomponents of it have those modules available.
- Expose dependencies so that other Components that depends on this one can access them.
Before the refactoring, you could find modules in a component defined multiple times. Why?
Since Plaid doesn't structure the Dagger graph with SubComponents. CoreComponent wasn't used as expected. It was never injected to an app component, imported 6 modules and didn't expose any dependency. Those 6 modules created Providers in the CoreComponentDagger generated file that weren't used by any other Component that had CoreComponent as a …
> Refactor Dagger components to use CoreComponent

- about/src/main/java/io/plaidapp/about/dagger/AboutActivityModule.kt
- about/src/main/java/io/plaidapp/about/dagger/AboutComponent.kt
- app/src/main/java/io/plaidapp/dagger/HomeComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/CoreComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/CoreDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/DataManagerModule.kt
- core/src/main/java/io/plaidapp/core/dagger/MarkdownModule.kt
- core/src/main/java/io/plaidapp/core/dagger/ProductHuntModule.kt
- core/src/main/java/io/plaidapp/core/dagger/SharedPreferencesModule.kt
- core/src/main/java/io/plaidapp/core/dagger/SourcesRepositoryModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/DesignerNewsDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/UpvoteStoryServiceComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/UpvoteStoryServiceModule.kt
- core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/scope/FeatureScope.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/DataModule.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/LoginComponent.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/StoryComponent.kt
- designernews/src/main/java/io/plaidapp/designernews/dagger/StoryModule.kt
- designernews/src/main/java/io/plaidapp/designernews/data/comments/CommentsRemoteDataSource.kt
- designernews/src/main/java/io/plaidapp/designernews/data/comments/CommentsRepository.kt
- designernews/src/main/java/io/plaidapp/designernews/data/users/UserRepository.kt
- designernews/src/main/java/io/plaidapp/designernews/data/votes/VotesRepository.kt
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleComponent.kt
- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleModule.kt
- search/src/main/java/io/plaidapp/search/dagger/SearchComponent.kt
With scopes, you can keep a single instance of a class as long as that scope exists. The Component defines the Scope that is used in its dependencies with an annotation in its interface declaration.
```
@Component(modules = [CoreDataModule::class])
@Singleton
interface CoreComponent {}
```
For this to work, the Component needs to be annotated with a scope. Then, the modules that the component includes must be also annotated with that particular scope. Let's take a look at an example:
In Plaid, CoreComponent acts as the BaseComponent that most components depends on. Since there's only an instance of the CoreComponent in the app lifecycle (in our case created in PlaidApplication.kt), the objects created with that Component will live until the application dies. With that definition, we could …
> Use Scopes to make objects have Component lifecycle

- search/src/main/java/io/plaidapp/search/domain/LoadSearchDataUseCase.kt
The previous implementation used a custom `CoroutineScope` that shouldn't be used as per https://medium.com/@elizarov/coroutine-context-and-scope-c8b255d59055
This uses `supervisorScope` instead. 
As per Sean McQuillan:
If you're trying to make a function that launches a coroutine that's intended to live longer than the caller, then taking CoroutineScope as an argument (or having it as a member e.g. viewModelScope) is the right way to structure that
If you're trying to make a function that launches a coroutine that will follow the rules of structured concurrency, then you can use coroutineScope {} and supervisorScope {}
Unit tests
> Add SupervisorScope to LoadSearchDataUseCase

- core/src/main/java/io/plaidapp/core/ui/transitions/DarkenImage.kt
Check if the `drawable` in an `ImageView` is `null` before creating an `Animator` over it in the `DarkenImage` transition.
Fixes #691
Manually on device.
> Ensure ImageView.drawable is not null before attempting to darken it.

- core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt
Restore the GIF indicator on Dribbble images in the grid.
We were previously looking for a certain css class which seems to have changed. Altered the `DribbbleSearchConverter` (gross 😷) logic to look for images with a `.gif` extension.
Fixes #699 
Manually.
none
> Fix GIF badge on Dribbble shots.

- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotBindingAdapters.kt
- dribbble/src/main/res/layout/activity_dribbble_shot.xml
Fixes Dribbble description animation.
Fixes #675 
For some reason, the transition doesn't like the BindingAdapter `goneUnless`. Even if we modify the adapter to only set the new visibility when it changes, the animation stops working. 
My gut tells me that the view is always GONE because we emit a first ShotUiModel with an empty description and then when the description is loaded, we emit another model with description making the animation for that view to stop working. 
That's why the decision is to set the visibility to GONE in the htmlText BindingAdapter when the description is null.
Manually.
None.
> Fixes Dribbble description animation

- app/src/main/java/io/plaidapp/ui/HomeActivity.java
Add a tooltip text to the dark theme toggle menu item.  After the change, a long press will show the "Toggle theme" text.
`TooltipCompat.setTooltipText` is needed due to the minApi (23) for the app, as the platform `.setTooltipText` was introduced in API 26.
The user can now long press on the dark mode toggle menu item to see what it does.  This functionality now matches the rest of the menu items.
Manual
N/A
> Add tooltip text to dark theme menu toggle

- app/src/main/java/io/plaidapp/ui/HomeActivity.kt
The layout manager was never being set on the grid layout.
Fixes #711
> Fix launch TypeCastException

- build.gradle
- core/src/main/java/io/plaidapp/core/designernews/data/api/DesignerNewsService.kt
- core/src/main/java/io/plaidapp/core/designernews/data/login/LoginRemoteDataSource.kt
- core/src/main/java/io/plaidapp/core/designernews/data/stories/StoriesRemoteDataSource.kt
- core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchService.kt
- core/src/main/java/io/plaidapp/core/dribbble/data/search/SearchRemoteDataSource.kt
- core/src/main/java/io/plaidapp/core/producthunt/data/ProductHuntRemoteDataSource.kt
- core/src/main/java/io/plaidapp/core/producthunt/data/api/ProductHuntService.kt
- core/src/test/java/io/plaidapp/core/designernews/data/login/LoginRemoteDataSourceTest.kt
- core/src/test/java/io/plaidapp/core/designernews/data/stories/StoriesRemoteDataSourceTest.kt
- core/src/test/java/io/plaidapp/core/dribbble/data/search/SearchRemoteDataSourceTest.kt
- core/src/test/java/io/plaidapp/core/producthunt/data/ProductHuntRemoteDataSourceTest.kt
- core/src/test/java/io/plaidapp/core/producthunt/data/api/FakeProductHuntService.kt
- designernews/src/main/java/io/plaidapp/designernews/data/api/DesignerNewsService.kt
- designernews/src/main/java/io/plaidapp/designernews/data/comments/CommentsRemoteDataSource.kt
- designernews/src/main/java/io/plaidapp/designernews/data/users/UserRemoteDataSource.kt
- designernews/src/main/java/io/plaidapp/designernews/data/votes/VotesRemoteDataSource.kt
- designernews/src/test/java/io/plaidapp/designernews/data/comments/CommentsRemoteDataSourceTest.kt
- designernews/src/test/java/io/plaidapp/designernews/data/users/UserRemoteDataSourceTest.kt
- designernews/src/test/java/io/plaidapp/designernews/data/votes/VotesRemoteDataSourceTest.kt
- designernews/src/test/java/io/plaidapp/designernews/domain/GetCommentsWithRepliesAndUsersUseCaseIntegrationTest.kt
- gradle/wrapper/gradle-wrapper.properties
Adds new Retrofit 2.6.0 `suspend` modifier to Retrofit interfaces.
No need to call `.await()` on those functions anymore because it's a `suspend` function instead of it returning a `Deferred` object.
Unit tests run locally
> Updates to Retrofit 2.6.0

- app/build.gradle
- build.gradle
Stop adding git SHA to the generated `BuildConfig` class.
It wasn't used anywhere, the idea was to potentially add this to crash reports etc but was never implemented. Changing the `BuildConfig` class on every build degrades build performance (see #718).
Manually
none
> Stop adding git SHA to BuildConfig.

- build.gradle
- core/src/main/java/io/plaidapp/core/dagger/CoreComponent.kt
- core/src/main/java/io/plaidapp/core/dagger/CoreDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/ProductHuntModule.kt
- core/src/main/java/io/plaidapp/core/dagger/designernews/DesignerNewsDataModule.kt
- core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
- core_dependencies.gradle
- designernews/src/main/java/io/plaidapp/designernews/dagger/DataModule.kt
After https://github.com/android/plaid/pull/716, the Retrofit Coroutines Adapter is no longer needed.
Unit tests and running the app in the emulator
> Removes Retrofit coroutines adapter library

- about/build.gradle
- app/build.gradle
- build.gradle
- core/build.gradle
- designernews/build.gradle
- dribbble/build.gradle
- search/build.gradle
- test_shared/build.gradle
- third_party/bypass/build.gradle
The following line has been extracted from all `build.gradle` files into the `subprojects {}` block.
```
apply from: '../repositories.gradle'
```
I was looking through #615 and spotted that all `build.gradle` files have the `apply from: 'repositories.gradle'` line. This change is just reducing the clutter in each of the `build.gradle` files.
1. All modules have similar `android { defaultConfig }` configuration which could also be deduplicated and extracted into the `subprojects {}` block. Let me know if this is something worth doing.
2. `apply plugin: 'kotlin-android'` can also be extracted to `subprojects {}` but that would bring issues if some non-Android modules are planned.
> Deduplicate configuration of repositories in build.gradle files

- about/src/main/java/io/plaidapp/about/ui/adapter/AboutPagerAdapter.kt
- about/src/main/res/layout/about_icon.xml
- about/src/main/res/layout/about_libs.xml
- about/src/main/res/layout/about_plaid.xml
- about/src/main/res/layout/activity_about.xml
- core/src/main/java/io/plaidapp/core/util/BindingAdapters.kt
- core/src/main/res/values-v29/colors.xml
- core/src/main/res/values/colors.xml
- core/src/main/res/values/styles.xml
- designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryActivity.java
- designernews/src/main/res/values/styles.xml
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotActivity.kt
- dribbble/src/main/res/layout/activity_dribbble_shot.xml
- dribbble/src/main/res/values/styles.xml
- search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
- search/src/main/res/values/styles.xml
Update all screens to draw edge-to-edge.
This better supports gesture nav on Q+ devices, which may have minimal system UI.
Updated all screens to draw behind the navigation bar. Pre-Q we use a semi-transparent scrim to provide background protection for the nav buttons. On Q+ we set transparent nav bars (system will provide a scrim in 3-button nav mode).
Used @chrisbanes' [Data Binding adapters](https://medium.com/androiddevelopers/windowinsets-listeners-to-layouts-8f9ccc8fa4d1) to ease this on screens already using DB but used manual `WindowInsetListener`s on screens not yet using DB.
Manually.
- Screens updating to Kotlin/Data Binding can be updated to use the Ext Funs or binding adapters.
- Update `DrawerLayout` to gesture friendly version when shippable artifact available.
> Draw edge-to-edge

- designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryActivity.java
- designernews/src/main/res/layout/designer_news_story_description.xml
Removed UI action handling of Designer News Stories and Comments upvotes.
Designer News Server API have currently disabled upvotes of Stories and comments. This change avoid that an user tried to upvote something and fail.
No new features to test.
Remove underlying functionality that handle upvotes.
> Removed UI handling UpVotes for Stories and Comments

- core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt
Href was empty in "a.dribbble-link" so i set correct path of htmlUrl in parseShot function
Dribbble Shots link were not correct. Now on dribble pic click it navigate to correct URL.
Manually
> Fix htmlUrl on Dribbble shots

- dribbble/src/main/java/io/plaidapp/dribbble/dagger/DribbbleModule.kt
- dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotActivity.kt
Removed the `ChromeFader` from Dagger injection for Dribbble's `ShotActivity`
Fixes #722 - happened because the injection of `ChromeFader` happening before the activity setContentView (because of the lazy delegate). The `ChromeFader` sees that the activity has no content view yet and sets status bar alpha to 0.  I think the cleanest solution is to just remove the `ChromeFader` from the injection, so we get to keep the lazy delegate (yay Kotlin)
Just visually inspected it on my device (Xiaomi Mi A1, API 28).
> #722 - remove SystemChromeFader from Dagger in Dribbble ShotActivity

- pull_request_template.md
Update `pull_request_template.md` to identify the UI changes easier in the section "**Screenshots / GIFs"**
When a screenshot is added looks biggest so it's complicated to review or understand the UI changes. (Here an example -> https://github.com/android/plaid/pull/721)
manually
The UI changes will be easy to identify
**Before**
**After**
> Support screenshots resizing in the PR Template

- about/src/main/java/io/plaidapp/about/ui/model/AboutViewModel.kt
- about/src/main/java/io/plaidapp/about/ui/model/AboutViewModelFactory.kt
- designernews/src/main/java/io/plaidapp/designernews/ui/DesignerNewsViewModelFactory.kt
- search/src/main/java/io/plaidapp/search/ui/SearchViewModelFactory.kt
`AboutViewModelFactory` injects an instance of `AboutViewModel` into itself which is in turn injected into `AboutActivity` every time the activity is created or recreated, causing an unused instance to be generated even when a reused instance is provided by `viewModels { … }`.
I was going through various `ViewModelProvider.Factory` implementations and I stumbled across this inconsistency which had been bugging me 😂 
Manually ran tests and built locally
Other instances of `ViewModelProvider.Factory` are not internal, I would rather keep them all internal but I opted for consistency, though I can update the others to be internal if requested.
I've been using a mechanism for generating `ViewModel` providers in our project which uses a similar style to what is done here, however instead of …
> Align creation of ViewModels

- about/src/main/res/layout/about_icon.xml
- about/src/main/res/layout/about_libs.xml
- about/src/main/res/layout/about_plaid.xml
- designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryActivity.java
- dribbble/src/main/res/layout/activity_dribbble_shot.xml
- search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
Fixes some issues with content overlapping navigation bar.
#721 implemented edge-to-edge drawing but missed a few things, especially in landscape. This PR fixes these.
Fixes #753 
Manually
None.
> Fixes some window inset issues.

- about/src/test/java/io/plaidapp/about/ui/model/AboutViewModelTest.kt
- app/src/test/java/io/plaidapp/ui/HomeViewModelTest.kt
- build.gradle
- designernews/src/androidTest/java/io/plaidapp/designernews/data/database/LoggedInUserDaoTest.kt
- designernews/src/test/java/io/plaidapp/designernews/ui/login/LoginViewModelTest.kt
- designernews/src/test/java/io/plaidapp/designernews/ui/story/StoryViewModelTest.kt
- dribbble/src/test/java/io/plaidapp/dribbble/ui/shot/ShotViewModelTest.kt
- gradle/wrapper/gradle-wrapper.properties
- search/src/test/java/io/plaidapp/search/ui/SearchViewModelTest.kt
- test_shared/src/main/java/io/plaidapp/test/shared/LiveDataTestUtil.kt
Changes usages of LiveDataTestUtil for getValue for getOrAwaitValue LiveData extension function
The recommended way to test LiveData emissions is with the getOrAwaitValue function.
https://medium.com/androiddevelopers/unit-testing-livedata-and-other-common-observability-problems-bb477262eb04
Unit tests
> Uses new method getOrAwaitValue to test LiveData emissions

- .circleci/config.yml
- about/src/main/java/io/plaidapp/about/ui/widget/CutoutTextView.kt
- build.gradle
- core/src/main/java/io/plaidapp/core/ui/widget/BadgedFourThreeImageView.kt
- core/src/main/java/io/plaidapp/core/ui/widget/CollapsingTitleLayout.java
- core/src/test/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverterTest.kt
Updates circle CI Android API 29
Maintenance
Waiting for circle to pass
Address other PRs blocked by this change
> Update circleci to api-29

- about/build.gradle
- app/build.gradle
- build.gradle
- core/build.gradle
- designernews/build.gradle
- dribbble/build.gradle
- scripts/greclipse.properties
- search/build.gradle
- test_shared/build.gradle
- third_party/bypass/build.gradle
- Added spotless rule for Groovy build scripts
- Added groovy configuration (script/greclipse.properties)
- Fixed spotless issues in multiple build.gradle files.
Fixes #808
Adding Spotless rules for Groovy Gradle files:
- Added spotless rule for Groovy build scripts
- Added groovy configuration (script/greclipse.properties)
- Fixed spotless issues in multiple build.gradle files.
For consistency in build.gradle files we can use the spotless plugin to enforce a consistent formatting.
Profit from the added spotless rules!
> Adding Spotless rules for Groovy Gradle files and fixes.

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
This updates Gradle wrapper to `5.6.4`, including some changes to `gradle.properties` that bring the file closer to the default template. Note that the Gradle Daemon is enabled by default, so the following line is not needed:
```
org.gradle.daemon=true
```
> Update Gradle wrapper to 5.6.4

- build.gradle
Android Studio 3.6 is now available:
https://androidstudio.googleblog.com/2020/02/android-studio-36-available-in-stable.html
EDIT:
Requires #792 to be merged first. I'll rebase this PR once #792 is on `master`.
> Update Android Gradle plugin to 3.6.0

- app/src/main/res/values/styles.xml
- `materialThemeOverlay` doesn't work with AppCompatToolbar
- since the style is being set explicitly (activity_home), we can use `android:theme`, and this will be applied as an overlay
- the popup menu is already taking `colorSurface` correctly, but not sure why it's not setting the text accordingly. Overriding textColorPrimary to colorOnSurface fixes it, while applying it in a small scope (only to the HomeToolbar's popupTheme) means we won't goof anything else up
Fixes #801 - PopMenu has always white text even when in light mode
Visually - see screenshots
Wait for comments
Before (dark mode) | After
---|---
Before (light mode) | After
---|---
> [801] Fix HomeToolbar popupTheme in non-night mode

- build.gradle
A small patch update to the Android Gradle plugin
https://androidstudio.googleblog.com/2020/02/android-studio-361-available.html
> Update Android Gradle plugin to 3.6.1
