README.md

Changed link to point to beta testing page

Chage link in README

---

gradle/wrapper/gradle-wrapper.properties

Please see #72
If you merge the 'backport' branch soon, please close this PR :relieved:

Upgrade gradle-wrapper to 2.10

---

app/src/main/java/io/plaidapp/data/api/dribbble/ShotLikesDataManager.java

I only fixed the one spot that was crashing for me when testing my other changes, so this is probably not a sufficient PR to merge. But opening it anyway to raise the issue and propose a simple solution.

Check response status before reading body

---

app/src/main/java/io/plaidapp/ui/DribbbleLogin.java
app/src/main/res/layout/activity_dribbble_login.xml
app/src/main/res/values/strings.xml

- Fixes NPE when the dribble login response body is null
- Replaces Toast for a TextView

Fixes NPE when response body is null and adds visual indicator

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/plaidapp/ui/ShareDribbbleImageTask.java
app/src/main/res/values/strings.xml

@nickbutcher please review and merge if you think these are good changes.

FileProvider: Create files authority inside build.gradle

---

app/src/main/java/io/plaidapp/ui/AboutActivity.java
app/src/main/res/layout/library.xml
app/src/main/res/values/styles.xml

Adds a description to each of the libraries that Plaid is using.
Also, changes public modifier to package modifier for some classes and
variables
@nickbutcher please review and merge if you think is a good improvement.

Adds a description to each of the libraries that Plaid is using

---

app/src/main/java/io/plaidapp/ui/drawable/MorphDrawable.java
app/src/main/java/io/plaidapp/ui/drawable/ThreadedCommentDrawable.java
app/src/main/java/io/plaidapp/ui/widget/BadgedFourThreeImageView.java
app/src/main/java/io/plaidapp/ui/widget/CollapsingTitleLayout.java
app/src/main/java/io/plaidapp/ui/widget/InkPageIndicator.java

Using Android Studio Analyze -> Inspect Code it reports various issues, fix a couple here.

Fix some issues reported by analyzing the code

---

app/src/main/java/io/plaidapp/ui/DesignerNewsLogin.java
app/src/main/res/layout/activity_dribbble_login.xml
app/src/main/res/layout/dribbble_comment.xml
app/src/main/res/values/strings.xml

Hi,
I extracted all hardcoded strings to reuse them if it would be possible. Hope you would find it useful.
Cheers!

Extracting hardcoded strings. Reusing them if it is possible.

---

app/src/main/java/io/plaidapp/ui/widget/InkPageIndicator.java

This PR allows the color of the InkPageIndicator's unselected and selected color from code.

Allow InkPageIndicator colors to be updated programmatically

---

app/src/main/java/io/plaidapp/ui/PlayerSheet.java
app/src/main/res/drawable/asl_close_down.xml
app/src/main/res/layout/player_sheet.xml

Use an AnimatedStateListDrawable for the close-to-down avd in the player sheet screen.

use asl for close to down avd

---

app/src/main/java/io/plaidapp/ui/widget/ElasticDragDismissFrameLayout.java

As described in issue #185 and in [this][YT] video, this
widget behave really weirdly when the scroll is performed
quickly, like a beginning of a fling gesture.
This is due to the 'returning' animation made in onStopNestedScroll.
Indeed, this method is called by the framework when ACTION_DOWN is
performed as a 'defensive cleanup for new gestures'.
This commit fixes it by retrieving the last actionEvent from
onInterceptTouchEvent, and perform the animation only if the last
actionEvent is not a ACTION_DOWN event.
Closes #185
[YT]: https://youtu.be/t-kYvsXIDoM

Fix ElasticDragDismissFrameLayout bump on fast scroll

---

app/src/main/java/io/plaidapp/data/api/DenvelopingConverter.java
app/src/main/java/io/plaidapp/data/api/designernews/model/Comment.java
app/src/main/java/io/plaidapp/data/api/designernews/model/Story.java
app/src/main/java/io/plaidapp/data/api/dribbble/model/Shot.java
app/src/main/java/io/plaidapp/data/api/producthunt/model/Post.java
app/src/main/java/io/plaidapp/ui/AboutActivity.java
app/src/main/java/io/plaidapp/ui/DesignerNewsLogin.java
app/src/main/java/io/plaidapp/ui/DesignerNewsStory.java
app/src/main/java/io/plaidapp/ui/DribbbleShot.java
app/src/main/java/io/plaidapp/ui/FeedAdapter.java
app/src/main/java/io/plaidapp/ui/FilterAdapter.java
app/src/main/java/io/plaidapp/ui/HomeActivity.java
app/src/main/java/io/plaidapp/ui/PlayerActivity.java
app/src/main/java/io/plaidapp/ui/PlayerSheet.java
app/src/main/java/io/plaidapp/ui/PostNewDesignerNewsStory.java
app/src/main/java/io/plaidapp/ui/SearchActivity.java
app/src/main/java/io/plaidapp/ui/widget/BottomSheet.java
app/src/main/java/io/plaidapp/ui/widget/InkPageIndicator.java
app/src/main/java/io/plaidapp/ui/widget/PasswordEntry.java
app/src/main/java/io/plaidapp/util/ParcelUtils.java
app/src/main/java/io/plaidapp/util/TransitionUtils.java

This CL was mostly automated using Android Studio (i.e. "Analyze" --> "Inspect code" and then I used quick fixes to replace anonymous classes with lambdas and method references).

Use lambdas and method references when possible

---

app/proguard-rules.pro

ProGuard rules cleanup

---

app/build.gradle
app/src/main/java/io/plaidapp/data/BaseDataManager.java

Caught this during Tor's talk at I/O and I can't unsee it.

Fix build config typo

---

app/build.gradle
app/src/main/java/io/plaidapp/data/BaseDataManager.java
app/src/main/java/io/plaidapp/data/DataManager.java
app/src/main/java/io/plaidapp/data/LoadSourceCallback.kt
app/src/main/java/io/plaidapp/data/SearchDataManager.java
app/src/main/java/io/plaidapp/data/api/designernews/DesignerNewsRepository.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties
third_party/bypass/src/main/AndroidManifest.xml

Removing DesignerNews from BaseDataManager and using it only where needed.

Encapsulating work with Designer News in a repo.

---

.circleci/config.yml
app/build.gradle
features/activities/build.gradle
third_party/bypass/build.gradle

Temporarily muting lint errors during initial CI setup.
Addresses #280

Add initial config for CircleCI

---

app/src/main/res/transition/home_enter.xml

Remove FAB Pop transition on app launch.

---

app/src/main/java/io/plaidapp/ui/FeedAdapter.java
features/activities/src/main/java/io/plaidapp/ui/designernews/DesignerNewsStory.java

Allowing an almost empty screen, so we can split the UI and the business work.

Allowing comment click on DN story

---

.circleci/config.yml
ci_scripts/copy_lint_results.sh

Update CI to gather and store all lint results

---

base/src/main/java/io/plaidapp/base/ui/widget/CollapsingTitleLayout.java
designernews/src/main/res/layout-w600dp/activity_designer_news_story.xml
designernews/src/main/res/layout/activity_designer_news_story.xml

Fix title on Designer News story screen.

---

app/build.gradle
app/google-services.json
build.gradle

Add Crashlytics.

---

README.md

Add instructions to configure ktlint styles in Android Studio

---

app/build.gradle
app/src/main/AndroidManifest.xml

Only enable Crashlytics logging in release builds.

---

app/build.gradle
build.gradle
dribbble/build.gradle

Address wrongly set filesAuthority

---

.gitignore

Some people would push a massive large file if it is not ignored.

Fix, gitignore ktlint

---

build.gradle
designernews/src/main/res/layout/designer_news_comment.xml

Fix designer news comment layout.

---

about/src/main/java/io/plaidapp/about/ui/adapter/LibraryHolder.kt
about/src/main/java/io/plaidapp/about/ui/model/AboutViewModelFactory.kt
about/src/main/java/io/plaidapp/about/ui/widget/CutoutTextView.kt
about/src/main/java/io/plaidapp/about/ui/widget/InkPageIndicator.java

- Warnings with annotations are added.
- Strange line wrapping fixed
- Code optimize of onClick() on library being clicked, no duplicated
connect to listener.

Fix lint/IDE warnings in "About" module

---

core/build.gradle
core/src/main/java/io/plaidapp/core/dribbble/data/DribbbleRepository.kt
core/src/main/java/io/plaidapp/core/dribbble/data/api/model/Images.kt
core/src/main/java/io/plaidapp/core/dribbble/data/api/model/Shot.kt
core/src/main/java/io/plaidapp/core/dribbble/data/api/model/User.kt
core/src/main/java/io/plaidapp/core/ui/FeedAdapter.java
core/src/main/java/io/plaidapp/core/util/ActivityHelper.kt
core/src/test/java/io/plaidapp/core/dribbble/data/DribbbleRepositoryTest.kt
dribbble/src/main/java/io/plaidapp/dribbble/Injection.kt
dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/DribbbleShotActivity.kt
dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/DribbbleShotViewModel.kt
dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/DribbbleShotViewModelFactory.kt
dribbble/src/test/java/io/plaidapp/dribbble/TestData.kt
dribbble/src/test/java/io/plaidapp/dribbble/domain/GetShareShotInfoUseCaseTest.kt
dribbble/src/test/java/io/plaidapp/dribbble/ui/shot/DribbbleShotViewModelTest.kt

Cache shots in Dribbble repo and retrieve in the VM.

---

core/src/androidTest/java/io/plaidapp/core/util/TextViewExtensionTest.kt
scripts/ftl_run_tests.sh

PR also converts tabs to spaces.

[WIP] Store exit code for gcloud command and return it when script finishes

---

build.gradle

https://plugins.jetbrains.com/plugin/6954-kotlin

Update kotlin to 1.2.60

---

core/src/main/java/io/plaidapp/core/util/delegates/ContentViewBindingDelegate.kt

The Know-How of `ContentViewBindingDelegate`  is perfect, this class is magic, however, there're some warnings given by IDE/lint.

Optimize ContentViewBindingDelegate for IDE/Lint warnings

---

core/src/main/java/io/plaidapp/core/designernews/data/comments/CommentsRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/designernews/data/login/LoginRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/designernews/data/stories/StoriesRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/designernews/data/users/UserRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/designernews/data/votes/VotesRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/dribbble/data/search/SearchRemoteDataSource.kt
core/src/main/java/io/plaidapp/core/util/NetworkUtils.kt
core/src/test/java/io/plaidapp/core/designernews/data/comments/CommentsRemoteDataSourceTest.kt
core/src/test/java/io/plaidapp/core/designernews/data/login/LoginRemoteDataSourceTest.kt
core/src/test/java/io/plaidapp/core/designernews/data/stories/StoriesRemoteDataSourceTest.kt
core/src/test/java/io/plaidapp/core/designernews/data/users/UserRemoteDataSourceTest.kt
core/src/test/java/io/plaidapp/core/designernews/data/votes/VotesRemoteDataSourceTest.kt
core/src/test/java/io/plaidapp/core/dribbble/data/search/SearchRemoteDataSourceTest.kt

Adds try/catch for all network requests

---

core/src/androidTest/java/io/plaidapp/core/designernews/data/LoggedInUserDaoTest.kt
core/src/main/java/io/plaidapp/core/data/AppDatabase.kt
core/src/main/java/io/plaidapp/core/data/Converters.kt
core/src/main/java/io/plaidapp/core/designernews/data/users/model/LoggedInUser.kt
core/src/test/java/io/plaidapp/core/data/ConvertersTest.kt

Includes type converter for storing/retrieving upvotes from database.

Add upvotes property to LoggedInUser

---

core/src/main/java/io/plaidapp/core/data/SearchDataManager.java

Use the Dribble ShotsRepository in search also

---

designernews/src/main/java/io/plaidapp/designernews/ui/story/StoryViewModel.kt

https://github.com/nickbutcher/plaid/pull/498#issuecomment-418753284

Remove let{}  when use story.links

---

app/src/main/res/values/strings.xml
dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotActivity.kt
dribbble/src/main/res/values/strings.xml

Splitting up the code from #453  to make it easier to review

Cleaning up dribbble related resources.

---

core/src/main/java/io/plaidapp/core/util/HtmlParser.kt
core/src/main/java/io/plaidapp/core/util/HtmlUtils.java
dribbble/src/main/java/io/plaidapp/dribbble/ui/shot/ShotActivity.kt

Splits part of the HtmlUtils functionality to HtmlParser.

---

build.gradle
designernews/build.gradle
dribbble/build.gradle
gradle/wrapper/gradle-wrapper.properties

Resolves the issue raised in #526 with the recommended solution from the issue

AGP 3.3.0-beta-01 with suggested classpath fixes

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Requires Android Studio 3.4 canary from now on.
Fixes #561

Update to gradle 5.0

---

core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt
core/src/test/resources/dribbble_search.html

Dribbble changed their HTML for likes. Also, now, the likes tag can be missing completely in case the shot doesn't have any likes.

Fixing dribbble parsing issue that allows the search to run.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- Crashlytics
- Firebase
- Gradle
- Kotlin
Test: CI and manual tests

Update to latest versions of dependencies

---

core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt

Fixes https://github.com/nickbutcher/plaid/issues/497
Thanks @XinyueZ

Reduce call on non-null type from !isNullOrEmpty to isNotEmpty

---

about/src/main/java/io/plaidapp/about/ui/model/AboutViewModel.kt
about/src/main/res/layout/about_plaid.xml
about/src/main/res/values/strings.xml

Also, disables hyphenation, to avoid names being hyphenated.

Updating the contributors list

---

about/build.gradle
about/src/main/java/io/plaidapp/about/ui/AboutActivity.kt
about/src/main/res/layout/activity_about.xml

Fixes issue #630 - Add DataBinding to About
Tested on an emulator and everything worked so far
All tests pass

Add DataBinding to About screen

---

about/build.gradle
about/src/main/java/io/plaidapp/about/ui/AboutActivity.kt
about/src/main/java/io/plaidapp/about/ui/adapter/AboutPagerAdapter.kt
about/src/main/java/io/plaidapp/about/ui/widget/InkPageIndicator.java
about/src/main/res/layout/about_libs.xml
about/src/main/res/layout/activity_about.xml
build.gradle

Fixes issue #618 - Update the About screen to use the ViewPager2 library
Overall smooth migration. **Fix for page margin included**.
*This is my first contribution to an open source Android project. Feedback welcomed!
1. Added dependency to `:about` module
2. Switched from `ViewPager` to `ViewPager2` in `activity_about.xml`
3. Added page margin fix to `AboutActivity.kt`
4. Replaced old `PagerAdapter` extension with `RecyclerView.Adapter` in `AboutPagerAdapter.kt` and implemented member functions
5. Removed old `ViewPager.OnPageChangeListener` implementation in `InkPageIndicator.java` and replaced it with new `registerOnPageChangeCallback`

[618] Migration from ViewPager to ViewPager2

---

app/src/main/java/io/plaidapp/ui/HomeActivity.java
app/src/main/java/io/plaidapp/ui/HomeViewModel.kt
app/src/test/java/io/plaidapp/ui/HomeViewModelTest.kt
core/src/main/java/io/plaidapp/core/ui/PlaidItemsListExtension.kt
search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt

Pass columns when getting the feed in Home

---

app/src/main/java/io/plaidapp/dagger/HomeModule.kt
app/src/main/java/io/plaidapp/ui/HomeActivity.java
core/src/main/java/io/plaidapp/core/dagger/qualifier/IsPocketInstalled.kt
search/src/main/java/io/plaidapp/search/dagger/SearchModule.kt
search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt

re #537 
* adding `IsPocketInstalled` qualifier
* ~adding `FeedColumns` qualifier~
* ~injecting `FeedAdapter`~

[Dagger] Use @IsPocketInstalled dagger qualifier

---

app/build.gradle
build.gradle

Bump versionName to 1.0.9, and also bump gradle to 3.4.0-rc02

Release 1.0.9-1190

---

.circleci/config.yml

* Introduce executors
* Introduce commands
* Fix typo in store_test_results command

Update CircleCI config for v2.1

---

README.md

README: Point CircleCI integration to new location

---

build.gradle

When opening the project in stable channel AS, it automatically makes
this change.

Bump to latest stable gradle android plugin

---

about/src/main/java/io/plaidapp/about/ui/model/AboutViewModel.kt

Close https://github.com/android/plaid/issues/723

Replace support libraries with Jetpack on About.

---

about/src/main/java/io/plaidapp/about/ui/model/AboutViewModel.kt

Remove retrofit-coroutines adapter as no longer used.
Fixed Mokito image.
Fixed Crashlytics image and updated name.
Some of the libraries credited on the about screen were out of date or missing images.
Manually.
none

Clean up libraries page.

---

build.gradle

Just updating to the latest version of Kotlin as the app was using an older version.
Manual testing + `./gradlew test` was green

Update Kotlin to 1.3.40

---

pull_request_template.md

Comment out screenshots in the PR template as they're showing as broken images.

Comment out screenshot placeholders

---

build.gradle
core/src/main/res/values/attrs_reflow_text.xml
repositories.gradle
test_dependencies.gradle

Updates AGP to 3.6.0-slpha04 plus other updates:
- fabric
- appcompat
- kotlin
- crashalitics
Keep repository healthy
translate gradle files to Kotlin Script

Updates to AGP 3.6.0-alpha04 and other libraries

---

build.gradle

Increased the ViewPager2 version

Bump ViewPager2 version to beta

---

README.md

Updated version of Android Studio required to run the project.
It fixes #765

Update Android Studio version required

---

build.gradle
core/src/main/java/io/plaidapp/core/dagger/ProductHuntModule.kt
core/src/main/java/io/plaidapp/core/dagger/designernews/DesignerNewsDataModule.kt
core/src/main/java/io/plaidapp/core/dagger/dribbble/DribbbleDataModule.kt
core/src/main/java/io/plaidapp/core/designernews/data/api/ClientAuthInterceptor.kt
core/src/test/java/io/plaidapp/core/designernews/TestData.kt
core/src/test/java/io/plaidapp/core/designernews/data/api/DesignerNewsSearchConverterTest.kt
core/src/test/java/io/plaidapp/core/dribbble/data/TestData.kt
core/src/test/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverterTest.kt
core/src/test/java/io/plaidapp/core/producthunt/data/TestData.kt
designernews/src/main/java/io/plaidapp/designernews/dagger/DataModule.kt
designernews/src/main/java/io/plaidapp/designernews/data/api/ClientAuthInterceptor.kt
designernews/src/test/java/io/plaidapp/designernews/TestData.kt
designernews/src/test/java/io/plaidapp/designernews/data/users/UserRemoteDataSourceTest.kt

This PR is my proposal for #741 
Upgrading to OkHttp 4

Upgrade to OkHttp 4

---

build.gradle

Bump version of ViewPager2 dependency to 1.0.0 (Stable)
ViewPager2 1.0.0 was released today
App compiles and runs, no regression

Update ViewPager2 to 1.0.0 stable

---

.circleci/config.yml
about/src/main/java/io/plaidapp/about/ui/model/AboutViewModelFactory.kt

fix the error when click about.
yes , I test it.

fix the crash when click about

---

app/src/main/java/io/plaidapp/ui/HomeActivity.kt
app/src/main/res/layout/activity_home.xml
app/src/main/res/menu/main.xml

Fixes #799 refactoring the from Toolbar to AppCompat Toolbar.
This required moving around the setup of the toolbar and fixing a couple of layouts.
To get Menu updated when users login/log out from Designer News.
Manually
- [] I added tests to verify changes
None

Migrate to AppCompat Toolbar to get onPrepareOptionsMenu to work

---

about/build.gradle
app/build.gradle
build.gradle
core/build.gradle
designernews/build.gradle
dribbble/build.gradle
gradle.properties
search/build.gradle

* Centralise setting of kapt build cache 
* Introduce kapt compile avoidance in the build
According to [documentation](https://kotlinlang.org/docs/reference/kapt.html#compile-avoidance-for-kapt-since-1320) it should improve build incremental speed.
`./gradlew assembleDebug`
Merge and evaluate
Not the visial change

Build improvements

---

core/src/main/java/io/plaidapp/core/dribbble/data/search/DribbbleSearchConverter.kt
core/src/main/java/io/plaidapp/core/ui/widget/ParallaxScrimageView.java
core/src/main/java/io/plaidapp/core/util/CollapsingTextHelper.java
core/src/main/java/io/plaidapp/core/util/glide/PlaidGlideModule.java
core/src/main/res/font/roboto_mono.xml
third_party/bypass/src/main/AndroidManifest.xml

First banch of lint fixes
This is a showcase app. I think it should be an example of how to keep your project in good shape. 
Compile and run.
Continue with lint report fixes.
Partial fix for #745

Fix some lint warning
